# Generated by Django 4.2.7 on 2024-01-11 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('prix', models.IntegerField(default=500)),
                ('quantite_disponible', models.IntegerField(default=1)),
                ('catId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitVendu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.IntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant', models.FloatField(default=1000)),
                ('service', models.CharField(blank=True, max_length=10, null=True)),
                ('type_transaction', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ManyToManyField(through='back_end.ProduitVendu', to='back_end.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produitvendu',
            name='vente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.vente'),
        ),
    ]
