# Generated by Django 4.2.7 on 2024-01-13 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='catId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_set', to='back_end.categorie'),
        ),
    ]
